// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import dotenv from 'dotenv';
import path from 'path';
const envFile = process.env.NODE_ENV === 'prod' || process.env.NODE_ENV === 'production' ? '.env.prod' : '.env.dev';


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed:'tsx prisma/seed.ts'
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    
  },
});
